version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - php-fpm

  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --sql_mode=""
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_db
      - MYSQL_USER=task_db
      - MYSQL_PASSWORD=task_db
    ports:
      - 3308:3306

  php-fpm:
    build : ./docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www
    links:
      - db
    working_dir: /var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8020:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=1G
    depends_on:
      - db